server = {
	'SERVER_LISTEN_ON_LOCAL_IP':'0.0.0.0',
	'SERVER_LISTEN_ON_LOCAL_PORT':'8000'
}

exfiltration = {
	'SERVER_EXTERNAL_IP':'your_external_ip',
	'SERVER_EXTERNAL_PORT':'8000',
}

reverseshell = {
	'SERVER_EXTERNAL_IP':'your_external_ip',
	'SERVER_EXTERNAL_PORT':'4446',
}

persistence = {
	'BASE64_ENCODED_PAYLOAD_UTF16LE':'eQBvAHUAcgBfAGIAYQBzAGUANgA0AF8AdQB0AGYALQAxADYATABFAF8AZQBuAGMAbwBkAGUAZABfAHAAYQB5AGwAbwBhAGQA'
}
